name: Manual Version Bump and Sync
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  version-bump-and-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        run: |
          sed -i 's/version: "[0-9.]*"/version: "${{ github.event.inputs.version }}"/' plugin.user.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add plugin.user.js
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git push
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
